// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBObXKI13geaNphxsi9X8FsPRJ4zwAHBiI',
    appId: '1:161722356989:web:f93eb601a235e15ae65a94',
    messagingSenderId: '161722356989',
    projectId: 'examcell-993e0',
    authDomain: 'examcell-993e0.firebaseapp.com',
    databaseURL: 'https://examcell-993e0-default-rtdb.firebaseio.com',
    storageBucket: 'examcell-993e0.appspot.com',
    measurementId: 'G-F34C1PY1LS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1YpgYZvMeR4LondokOnR00bxpVva8v7U',
    appId: '1:161722356989:android:389e92b5b5616d8fe65a94',
    messagingSenderId: '161722356989',
    projectId: 'examcell-993e0',
    databaseURL: 'https://examcell-993e0-default-rtdb.firebaseio.com',
    storageBucket: 'examcell-993e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBkSlHlEI8SQ744Y--3xnleH4GWekdB-k',
    appId: '1:161722356989:ios:015d4ed3a4ef3a2fe65a94',
    messagingSenderId: '161722356989',
    projectId: 'examcell-993e0',
    databaseURL: 'https://examcell-993e0-default-rtdb.firebaseio.com',
    storageBucket: 'examcell-993e0.appspot.com',
    iosClientId:
        '161722356989-dau3dc05q9gahadbs0aohvpvej9ui97g.apps.googleusercontent.com',
    iosBundleId: 'com.example.examcellapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBkSlHlEI8SQ744Y--3xnleH4GWekdB-k',
    appId: '1:161722356989:ios:04c207aa3dce4218e65a94',
    messagingSenderId: '161722356989',
    projectId: 'examcell-993e0',
    databaseURL: 'https://examcell-993e0-default-rtdb.firebaseio.com',
    storageBucket: 'examcell-993e0.appspot.com',
    iosClientId:
        '161722356989-gku2s8rggjat8h06o0c71p22j2k6gk9n.apps.googleusercontent.com',
    iosBundleId: 'com.example.examcellapp.RunnerTests',
  );
}
